### ISSUE TITLE
Need of two encoders and decoder of training

### ISSUE THREAD

**Issue by krips89** [rosinality/swapping-autoencoder-pytorch#11]
What is the need of two encoder (encoder and e_ema) during the trainign? 
And the same goes for the decoder

**Comment by rosinality** [comment]
It is running average of the encoder/decoder. Using running average of the model will show better results.

**Comment by krips89** [comment]
Any literature to back this up?

**Comment by rosinality** [comment]
I don't know which paper first tried to apply ema to the gan training. But you can refer to the papers like this. https://arxiv.org/abs/1806.04498

**Comment by krips89** [comment]
Thank you for the answer, does the official stylegan2 implement that? 
I'm closing this issue.

**Comment by rosinality** [comment]
Yes, stylegan2 also uses it.

**Comment by nobodypengium** [comment]
Hi, thanks for your implementation.
Is there any criterion to difine `accum` (the hyper-param for ema)
[code here](https://github.com/rosinality/swapping-autoencoder-pytorch/blob/master/train.py#L152)
`accum = 0.5 ** (32 / (10 * 1000))`
@rosinality

**Comment by rosinality** [comment]
@nobodypengium I took it from official stylegan2 implementations. It seems like that authors defined it in relation of number of seen images. (which is stylegan2 authors preferred way to define hyperparameters.) I think 0.999 ~ 0.9999 (biggan) works well. (Though stylegan2 uses about 0.998)

**Comment by nobodypengium** [comment]
Thanks for your answer!
