### ISSUE TITLE
Keyerror: 'args'

### ISSUE THREAD

**Issue by Nerdyvedi** [rosinality/swapping-autoencoder-pytorch#2]
Hi, 
Thank you so much for such a wonderful work. I was trying to reproduce the results, but I am getting keyerror on the following line:
`    args = parser.parse_args()

    ckpt = torch.load(args.ckpt, map_location=lambda storage, loc: storage)
    ckpt_args = ckpt["args"]`

Could you take a look at what might be wrong?
Thank you

**Comment by rosinality** [comment]
Could you show me the keys of checkpoint dict? Checkpoints should have 'args' key.

**Comment by Nerdyvedi** [comment]
@rosinality These are the keys I found in the checkpoint you shared in the last issue
['g', 'd', 'g_ema', 'g_optim', 'd_optim']

**Comment by rosinality** [comment]
Did you use this? https://drive.google.com/file/d/1JkQHADB-jydOyWVdlnvkVPSvTAjo9fE_ I think your checkpoint is not from this model.

**Comment by Nerdyvedi** [comment]
Ohh, Huh. I think I downloaded a different model from the same link. 
Got it. Thanks.
Great results!

@rosinality Is it possible to use this model for high resolution images ?

**Comment by rosinality** [comment]
I haven't tested it, but maybe it could work.

**Comment by Nerdyvedi** [comment]
Ok, Thanks!

**Comment by ak9250** [comment]
@rosinality I am getting this
Traceback (most recent call last):
  File "generate.py", line 78, in <module>
    imgs = torch.stack(imgs, 0)
RuntimeError: stack expects a non-empty TensorList
